spring:
  application:
    name: recipe_app
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:recipe_app}
    username: ${DB_USERNAME:recipe_app}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    time-zone:
      Asia/Seoul:


